# Woodpecker CI configuration (dbuild pipeline)
steps:
  - name: build
    image: /bin/sh
    environment:
      GITHUB_TOKEN:
        from_secret: GITHUB_TOKEN
      GITHUB_ACTOR:
        from_secret: GITHUB_USER
    commands:
      - fetch -qo dbuild-ci.sh "https://gitea.ahze.lan/ahze/daemonless/raw/branch/main/scripts/dbuild-ci.sh"
      - sh dbuild-ci.sh

when:
  - event: push
    branch: main
    path:
      exclude: ["*.md", "docs/**", "LICENSE", ".gitignore"]
  - event: manual
